// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for HeartbeatStatus.
const (
	Draining HeartbeatStatus = "draining"
	Ok       HeartbeatStatus = "ok"
)

// Defines values for ListenerConfigProtocol.
const (
	Http   ListenerConfigProtocol = "http"
	Https  ListenerConfigProtocol = "https"
	Socks4 ListenerConfigProtocol = "socks4"
	Socks5 ListenerConfigProtocol = "socks5"
)

// Defines values for RouteConfigEgressType.
const (
	RouteConfigEgressTypeLocal RouteConfigEgressType = "local"
	RouteConfigEgressTypeProxy RouteConfigEgressType = "proxy"
	RouteConfigEgressTypeSsh   RouteConfigEgressType = "ssh"
)

// Defines values for TunnelConfigType.
const (
	TunnelConfigTypeLocal TunnelConfigType = "local"
	TunnelConfigTypeProxy TunnelConfigType = "proxy"
	TunnelConfigTypeSsh   TunnelConfigType = "ssh"
)

// Error defines model for Error.
type Error struct {
	Code    *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// Gateway defines model for Gateway.
type Gateway struct {
	// ApiKey Use for subsequent config/heartbeat calls
	ApiKey    *string             `json:"api_key,omitempty"`
	CreatedAt *time.Time          `json:"created_at,omitempty"`
	Id        *openapi_types.UUID `json:"id,omitempty"`
}

// GatewayConfig defines model for GatewayConfig.
type GatewayConfig struct {
	Listeners *[]ListenerConfig `json:"listeners,omitempty"`
	Routes    *[]RouteConfig    `json:"routes,omitempty"`
	Tunnels   *[]TunnelConfig   `json:"tunnels,omitempty"`
	UpdatedAt *time.Time        `json:"updated_at,omitempty"`
}

// GatewayRegistration defines model for GatewayRegistration.
type GatewayRegistration struct {
	// Addrs Reachable addresses (host:port)
	Addrs   *[]string          `json:"addrs,omitempty"`
	Labels  *map[string]string `json:"labels,omitempty"`
	Version string             `json:"version"`
}

// Heartbeat defines model for Heartbeat.
type Heartbeat struct {
	Status       *HeartbeatStatus `json:"status,omitempty"`
	TunnelsCount *int             `json:"tunnels_count,omitempty"`
}

// HeartbeatStatus defines model for Heartbeat.Status.
type HeartbeatStatus string

// ListenerConfig defines model for ListenerConfig.
type ListenerConfig struct {
	DefaultAnonymousGroupId *openapi_types.UUID     `json:"default_anonymous_group_id"`
	DefaultGroupId          *openapi_types.UUID     `json:"default_group_id,omitempty"`
	Id                      *openapi_types.UUID     `json:"id,omitempty"`
	Port                    *int                    `json:"port,omitempty"`
	Protocol                *ListenerConfigProtocol `json:"protocol,omitempty"`
}

// ListenerConfigProtocol defines model for ListenerConfig.Protocol.
type ListenerConfigProtocol string

// RouteConfig defines model for RouteConfig.
type RouteConfig struct {
	EgressConfig *map[string]interface{} `json:"egress_config,omitempty"`
	EgressType   *RouteConfigEgressType  `json:"egress_type,omitempty"`
	GroupId      *openapi_types.UUID     `json:"group_id,omitempty"`
	Id           *openapi_types.UUID     `json:"id,omitempty"`
	ListenerId   *openapi_types.UUID     `json:"listener_id,omitempty"`
	TunnelId     *openapi_types.UUID     `json:"tunnel_id"`
}

// RouteConfigEgressType defines model for RouteConfig.EgressType.
type RouteConfigEgressType string

// TokenValidateRequest defines model for TokenValidateRequest.
type TokenValidateRequest struct {
	// Token User or gateway token
	Token string `json:"token"`
}

// TokenValidateResponse defines model for TokenValidateResponse.
type TokenValidateResponse struct {
	DefaultRouteId *openapi_types.UUID   `json:"default_route_id"`
	GroupIds       *[]openapi_types.UUID `json:"group_ids,omitempty"`

	// RouteId Resolved route for this token
	RouteId *openapi_types.UUID `json:"route_id"`

	// UserId Present when valid and token is user token
	UserId *openapi_types.UUID `json:"user_id,omitempty"`
	Valid  bool                `json:"valid"`
}

// TunnelConfig defines model for TunnelConfig.
type TunnelConfig struct {
	Config *map[string]interface{} `json:"config,omitempty"`
	Id     *openapi_types.UUID     `json:"id,omitempty"`

	// Static If true, keep alive; if false, on-demand
	Static *bool             `json:"static,omitempty"`
	Type   *TunnelConfigType `json:"type,omitempty"`
}

// TunnelConfigType defines model for TunnelConfig.Type.
type TunnelConfigType string

// GatewayId defines model for GatewayId.
type GatewayId = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// GetGatewayConfigParams defines parameters for GetGatewayConfig.
type GetGatewayConfigParams struct {
	// GatewayId Gateway instance ID (if not in token)
	GatewayId *openapi_types.UUID `form:"gateway_id,omitempty" json:"gateway_id,omitempty"`
}

// ValidateTokenJSONRequestBody defines body for ValidateToken for application/json ContentType.
type ValidateTokenJSONRequestBody = TokenValidateRequest

// RegisterGatewayJSONRequestBody defines body for RegisterGateway for application/json ContentType.
type RegisterGatewayJSONRequestBody = GatewayRegistration

// GatewayHeartbeatJSONRequestBody defines body for GatewayHeartbeat for application/json ContentType.
type GatewayHeartbeatJSONRequestBody = Heartbeat

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ValidateTokenWithBody request with any body
	ValidateTokenWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ValidateToken(ctx context.Context, body ValidateTokenJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetGatewayConfig request
	GetGatewayConfig(ctx context.Context, params *GetGatewayConfigParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RegisterGatewayWithBody request with any body
	RegisterGatewayWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	RegisterGateway(ctx context.Context, body RegisterGatewayJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GatewayHeartbeatWithBody request with any body
	GatewayHeartbeatWithBody(ctx context.Context, gatewayId GatewayId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	GatewayHeartbeat(ctx context.Context, gatewayId GatewayId, body GatewayHeartbeatJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ValidateTokenWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewValidateTokenRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ValidateToken(ctx context.Context, body ValidateTokenJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewValidateTokenRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetGatewayConfig(ctx context.Context, params *GetGatewayConfigParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetGatewayConfigRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RegisterGatewayWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRegisterGatewayRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RegisterGateway(ctx context.Context, body RegisterGatewayJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRegisterGatewayRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GatewayHeartbeatWithBody(ctx context.Context, gatewayId GatewayId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGatewayHeartbeatRequestWithBody(c.Server, gatewayId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GatewayHeartbeat(ctx context.Context, gatewayId GatewayId, body GatewayHeartbeatJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGatewayHeartbeatRequest(c.Server, gatewayId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewValidateTokenRequest calls the generic ValidateToken builder with application/json body
func NewValidateTokenRequest(server string, body ValidateTokenJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewValidateTokenRequestWithBody(server, "application/json", bodyReader)
}

// NewValidateTokenRequestWithBody generates requests for ValidateToken with any type of body
func NewValidateTokenRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/internal/gateway/v1/auth/validate")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetGatewayConfigRequest generates requests for GetGatewayConfig
func NewGetGatewayConfigRequest(server string, params *GetGatewayConfigParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/internal/gateway/v1/config")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.GatewayId != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "gateway_id", runtime.ParamLocationQuery, *params.GatewayId); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRegisterGatewayRequest calls the generic RegisterGateway builder with application/json body
func NewRegisterGatewayRequest(server string, body RegisterGatewayJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRegisterGatewayRequestWithBody(server, "application/json", bodyReader)
}

// NewRegisterGatewayRequestWithBody generates requests for RegisterGateway with any type of body
func NewRegisterGatewayRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/internal/gateway/v1/gateways")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGatewayHeartbeatRequest calls the generic GatewayHeartbeat builder with application/json body
func NewGatewayHeartbeatRequest(server string, gatewayId GatewayId, body GatewayHeartbeatJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewGatewayHeartbeatRequestWithBody(server, gatewayId, "application/json", bodyReader)
}

// NewGatewayHeartbeatRequestWithBody generates requests for GatewayHeartbeat with any type of body
func NewGatewayHeartbeatRequestWithBody(server string, gatewayId GatewayId, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "gateway_id", runtime.ParamLocationPath, gatewayId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/internal/gateway/v1/gateways/%s/heartbeat", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ValidateTokenWithBodyWithResponse request with any body
	ValidateTokenWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ValidateTokenResponse, error)

	ValidateTokenWithResponse(ctx context.Context, body ValidateTokenJSONRequestBody, reqEditors ...RequestEditorFn) (*ValidateTokenResponse, error)

	// GetGatewayConfigWithResponse request
	GetGatewayConfigWithResponse(ctx context.Context, params *GetGatewayConfigParams, reqEditors ...RequestEditorFn) (*GetGatewayConfigResponse, error)

	// RegisterGatewayWithBodyWithResponse request with any body
	RegisterGatewayWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RegisterGatewayResponse, error)

	RegisterGatewayWithResponse(ctx context.Context, body RegisterGatewayJSONRequestBody, reqEditors ...RequestEditorFn) (*RegisterGatewayResponse, error)

	// GatewayHeartbeatWithBodyWithResponse request with any body
	GatewayHeartbeatWithBodyWithResponse(ctx context.Context, gatewayId GatewayId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GatewayHeartbeatResponse, error)

	GatewayHeartbeatWithResponse(ctx context.Context, gatewayId GatewayId, body GatewayHeartbeatJSONRequestBody, reqEditors ...RequestEditorFn) (*GatewayHeartbeatResponse, error)
}

type ValidateTokenResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TokenValidateResponse
	JSON401      *Unauthorized
}

// Status returns HTTPResponse.Status
func (r ValidateTokenResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ValidateTokenResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetGatewayConfigResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GatewayConfig
	JSON401      *Unauthorized
}

// Status returns HTTPResponse.Status
func (r GetGatewayConfigResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetGatewayConfigResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RegisterGatewayResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *Gateway
	JSON400      *BadRequest
}

// Status returns HTTPResponse.Status
func (r RegisterGatewayResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RegisterGatewayResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GatewayHeartbeatResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON401      *Unauthorized
}

// Status returns HTTPResponse.Status
func (r GatewayHeartbeatResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GatewayHeartbeatResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ValidateTokenWithBodyWithResponse request with arbitrary body returning *ValidateTokenResponse
func (c *ClientWithResponses) ValidateTokenWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ValidateTokenResponse, error) {
	rsp, err := c.ValidateTokenWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseValidateTokenResponse(rsp)
}

func (c *ClientWithResponses) ValidateTokenWithResponse(ctx context.Context, body ValidateTokenJSONRequestBody, reqEditors ...RequestEditorFn) (*ValidateTokenResponse, error) {
	rsp, err := c.ValidateToken(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseValidateTokenResponse(rsp)
}

// GetGatewayConfigWithResponse request returning *GetGatewayConfigResponse
func (c *ClientWithResponses) GetGatewayConfigWithResponse(ctx context.Context, params *GetGatewayConfigParams, reqEditors ...RequestEditorFn) (*GetGatewayConfigResponse, error) {
	rsp, err := c.GetGatewayConfig(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetGatewayConfigResponse(rsp)
}

// RegisterGatewayWithBodyWithResponse request with arbitrary body returning *RegisterGatewayResponse
func (c *ClientWithResponses) RegisterGatewayWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RegisterGatewayResponse, error) {
	rsp, err := c.RegisterGatewayWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRegisterGatewayResponse(rsp)
}

func (c *ClientWithResponses) RegisterGatewayWithResponse(ctx context.Context, body RegisterGatewayJSONRequestBody, reqEditors ...RequestEditorFn) (*RegisterGatewayResponse, error) {
	rsp, err := c.RegisterGateway(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRegisterGatewayResponse(rsp)
}

// GatewayHeartbeatWithBodyWithResponse request with arbitrary body returning *GatewayHeartbeatResponse
func (c *ClientWithResponses) GatewayHeartbeatWithBodyWithResponse(ctx context.Context, gatewayId GatewayId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GatewayHeartbeatResponse, error) {
	rsp, err := c.GatewayHeartbeatWithBody(ctx, gatewayId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGatewayHeartbeatResponse(rsp)
}

func (c *ClientWithResponses) GatewayHeartbeatWithResponse(ctx context.Context, gatewayId GatewayId, body GatewayHeartbeatJSONRequestBody, reqEditors ...RequestEditorFn) (*GatewayHeartbeatResponse, error) {
	rsp, err := c.GatewayHeartbeat(ctx, gatewayId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGatewayHeartbeatResponse(rsp)
}

// ParseValidateTokenResponse parses an HTTP response from a ValidateTokenWithResponse call
func ParseValidateTokenResponse(rsp *http.Response) (*ValidateTokenResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ValidateTokenResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TokenValidateResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseGetGatewayConfigResponse parses an HTTP response from a GetGatewayConfigWithResponse call
func ParseGetGatewayConfigResponse(rsp *http.Response) (*GetGatewayConfigResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetGatewayConfigResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GatewayConfig
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseRegisterGatewayResponse parses an HTTP response from a RegisterGatewayWithResponse call
func ParseRegisterGatewayResponse(rsp *http.Response) (*RegisterGatewayResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RegisterGatewayResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Gateway
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParseGatewayHeartbeatResponse parses an HTTP response from a GatewayHeartbeatWithResponse call
func ParseGatewayHeartbeatResponse(rsp *http.Response) (*GatewayHeartbeatResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GatewayHeartbeatResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}
